t: teste.cpp
	g++ -Wall -g teste.cpp -o output
	./output

struct_prontuario: struct_prontuario.c
	gcc -Wall -g struct_prontuario.c -o output
	./output <struct_prontuario.txt

testestring: testestring.cpp
	g++ -Wall -g testestring.cpp -o output
	./output <testes.txt

struct_alfabetica: struct_alfabetica.cpp
	g++ -Wall -g  struct_alfabetica.cpp -o output
	./output <testes.txt

struct_2: struct_alfabetica2.cpp
	g++ -Wall -g  struct_alfabetica2.cpp -o output
	./output <testes.txt

ponteiro_quantidade_igual: ponteiro_quantidade_igual.cpp
	g++ -Wall -g  ponteiro_quantidade_igual.cpp -o output
	./output

swap: swap_ponteiro.cpp
	g++ -Wall -g  swap_ponteiro.cpp -o output
	./output

base2: recursao_base_2.cpp
	g++ -Wall -g  recursao_base_2.cpp -o output
	./output

primo: primo_ou_nao.cpp
	g++ -Wall -g  primo_ou_nao.cpp -o output
	./output

clean:
	rm output

#CC = gcc
#CFLAGS = -o -Wall -g

#TARGET = comandosBasicos

#all: $(TARGET)
#$(TARGET): $(TARGET).c
#	$(CC) $(CFLAGS) $(TARGET).c -o $(TARGET) 	
#	./$(TARGET) <comandosBasicos.txt
# abcdefgh: abcdefgh.cpp
# 	gcc -Wall -g  abcdefgh.cpp -o output
# 	./output <testes