
comandosBasicos: comandosBasicos.c
	gcc -Wall -g comandosBasicos.c -o output
	./output

estruturasDeRepeticao: estruturasDeRepeticao.c
	gcc -Wall -g estruturasDeRepeticao.c -o output
	./output <estruturasDeRepeticao.txt

vetores: vetores.c
	gcc -Wall -g vetores.c -o output
	./output <vetores.txt

struct_prontuario: struct_prontuario.c
	gcc -Wall -g struct_prontuario.c -o output
	./output <struct_prontuario.txt

clean:
	rm output

#CC = gcc
#CFLAGS = -o -Wall -g

#TARGET = comandosBasicos

#all: $(TARGET)
#$(TARGET): $(TARGET).c
#	$(CC) $(CFLAGS) $(TARGET).c -o $(TARGET) 	
#	./$(TARGET) <comandosBasicos.txt